version: '3'
services:
  cardano-sl:
    image: jaen/cardano-sl-nix:57e2710549ff9079714f5b7d89c940cc38e8b6c1
    # build:
      # context: ./cardano-sl-nix
    network_mode: "host"
    ports:
      - "8090:8090"
    volumes:
      - ./wallet-state:/cardano-sl/state-wallet-mainnet
  daedalus:
    depends_on:
      - cardano-sl
    image: jaen/cardano-daedalus-fixed:a267ae05daaf3947fe679eac56d1257a8775b27b
    # build:
    #   context: ./daedalus
    network_mode: "host"
    environment:
      DISPLAY: "$DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./daedalus-config:/home/daedalus/.config/Daedalus
      - ./nssdb/:/home/daedalus/.pki/nssdb
